### ISSUE TITLE
HOL Guide - Task 3 - Register appliance in Azure Migrate

### ISSUE THREAD

**Issue by fyunis** [microsoft/MCW-Line-of-business-application-migration#95] opened 2022-04-24 23:55 UTC
Hello,
I was doing the lab, and when during the configuration of the Azure Migrate Appliance, in the second step, where we need to enter the key for register it, shows the following error, even when i enter the correct key:
![RegisterApp](https://user-images.githubusercontent.com/100795165/165001981-2aede116-0fc6-4ed3-b947-3668da565a76.png)

Maybe i missing something, please your support.

**Comment by tejaswini972** [comment] 2022-04-26 03:22
Hello @timahenning,

I have also faced the same issue while **registering the key with Azure Migrate** even though the Azure Migrate key is correct. The issue is with the **Azure migrate application version**, the current version is **outdated** due to which we are encountering the issue with the keys.

Could you please check on the same as we have workshops scheduled for today and tomorrow??

**Comment by codingbandit** [comment] 2022-04-27 00:52
@tejaswini972 and @fyunis - the VHD image was updated today to the latest image for the appliance. Unfortunately the issue with the project key still persists after testing. We will continue to investigate.

**Comment by DawnmarieDesJardins** [comment] 2022-04-27 18:15
Closing issue as resolved.  Thanks everyone!

**Closed by DawnmarieDesJardins** 2022-04-27 18:15 UTC
