### ISSUE TITLE
Issue Migrating the SQL Machine instead of using DMS

### ISSUE THREAD

**Issue by bengimblett** [microsoft/MCW-Line-of-business-application-migration#29] opened 2019-10-28 14:57 UTC
Hi, if you try and migrate the SQL machine with the web and WAF using ASR, as opposed to using DMS , as more of a straight lift and shift exercise, the SQL Machine will not come up properly in Azure.
It looks like its missing the following KB patch http://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4073562

The network card shows failed in the boot diagnostics image of the migrated SQL Machine. This leaves the Azure version of the VM inaccessible. SAC doesn't work either. 

I was able to fix this retrospectively by copying the OS disk, mounting it on a surrogate VM and applying the patch that way. Once the disk was swapped back out the SQL machine was accessible. I did not try applying the patch before ASR migrate - but this should work fine too.

More info: https://docs.microsoft.com/en-us/azure/virtual-machines/troubleshooting/troubleshoot-rdp-driver-netvsc#repair-the-vm-offline

**Comment by paulopsgility** [comment] 2019-10-28 17:00
@bengimblett thank you for the information, we only support the scenario documented in the lab guide (database migration via DMS). Unless I am missing something we do not do an ASR migration of the SQL Server. 

I'm going to mark this as won't fix for now. I'll leave it open for a little bit in case I am just not understanding what the issue is.

**Comment by bagwyth** [comment] 2019-10-29 17:43
@paulopsgility In my testing, downloading and installing all pending Windows updates to the SQL VM has the same effect that @bengimblett describes. That is, it enables an additional scenario of completing a lift-and-shift migration of the SQL VM with Azure Migrate as an alternative to modernising it to SQL PaaS.

**Comment by paulopsgility** [comment] 2019-10-31 17:10
OK, I see, yes, of course there are several scenarios for migration and different paths one might choose to get through each scenario. However, we have to choose one for the lab. The lab is not intended to step through all of the possibilities.

If you are saying that you think we should change the migration pattern used in the lab, you can open an issue as an enhancement request and we will triage it at the next update. 

Paul

**Comment by DawnmarieDesJardins** [comment] 2019-11-04 20:59
Closing issue. @bagwyth 
Barney - If you feel the current solution scenarion in the workshop should be changed, please open an issue describing the changes in detail.  This workshop is scheduled for an update in Q3 so we would love to hear your idea and it's benefits to learners.  We'll mark the issue as an enhancement and have our lead and SME group review it.

**Closed by DawnmarieDesJardins** 2019-11-04 20:59 UTC
Labels: wontfix
